### PR TITLE
Changed default to api-ssl as is the RouterOS.

### PR DESCRIPTION
**Pull request by eduardomazolini**
Changed default to use ssl to true and port to 8729 as is default in RouterOS enabled api-ssl.

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
I don't think the default needs to be SSL. There are a lot of applications where SSL isn't required.

**Comment by eduardomazolini** [comment]
@scottchiefbaker I also think not, but Mikrotik does. The only way to connect through the API without doing anything previously in RouterOS is by SSL ADH.

**Comment by Chupaka** [comment]
> The only way to connect through the API without doing anything previously in RouterOS is by SSL ADH

You mean, API is disabled by default and only API-SSL is enabled? On my routers, API is enabled by default, as I can see...

**Comment by BenMenking** [comment]
Cleanup

**Pull request closed without merging**
