### PR TITLE
Better SSL/TLS connection management

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
Hi,

I enhanced your library a little bit in order to provide a better SSL/TLS connection for the developer who wants to use this library.

Useful if you want to turn off some flags that with the current implementation ( forced to SSL only btw ) is not possible.

The code is tested and running. Hope you'll like it.

Enjoy :)

### CODE REVIEW

**Comment by BenMenking** [comment]
Looking over this patch, doesn't it always force encryption on the socket?

**Comment by BenMenking** [comment]
Since this forces crypto, has a merge conflict, and would prevent older devices with the api service from working, I can't accept this patch right now.  Adding crypto as an option would be helpful.

**Comment by julianxhokaxhiu** [comment]
What I am using are not `crypto` extensions but `Stream` extesions of PHP ( see http://php.net/manual/en/stream.installation.php and http://php.net/manual/en/function.stream-socket-enable-crypto.php ) which comes by default since PHP 4.3.0.

I would consider reopening the possibility to merge this PR and it would enhance user experience ( currently in use by a couple of friends ).

**Comment by BenMenking** [comment]
I'll take a look at it again.

**Comment by julianxhokaxhiu** [comment]
Ready to be merged, if you require less commits I can rebase if you prefer :)

**Comment by julianxhokaxhiu** [comment]
Hi, any update?

**Comment by julianxhokaxhiu** [comment]
Is there still any interest in this?

**Comment by julianxhokaxhiu** [comment]
It seems not.

**Pull request closed without merging**
