### PR TITLE
Added Custom Port Feature

### PR DESCRIPTION
**Pull request by ibnumalikalbust**
What do you think about the custom port feature?

### CODE REVIEW

**Comment by ibnumalikalbust** [comment]
Added Custom Port Feature

**Comment by Chupaka** [comment]
Can't you do it right now?..

```
$API = new RouterosAPI();

$API->port = 12345;

if ($API->connect('111.111.111.111', 'LOGIN', 'PASSWORD')) { ... }

**Comment by Chupaka** [comment]
And regarding the PR itself: you definitely don't need three commits. Squash is your friend.

**Comment by BenMenking** [comment]
Since the port can be set via the class property, we want to avoid breaking the connect() function signature.

**Pull request closed without merging**
