### PR TITLE
Fix reading equals

### PR DESCRIPTION
**Pull request by tristanharris**
This fixes issue #27 

Also includes making it easier to run the examples against different systems

### CODE REVIEW

**Comment by BenMenking** [comment]
Would like to keep the regular expressions and fix those.  Breaking out the configuration variables is good.  Can you re-submit w/o removing preg_match_all() or I can apply a commit.

**Comment by tristanharris** [comment]
Sorry, didn't get an alert about your comment.
What is the reasoning behind keeping the regex? It should be more efficient doing a simple character match

**Comment by BenMenking** [comment]
Arguably the preg_match_all() is clearer when reading the flow of the code than the explode() with a nested ltrim().  AFAIK there's not been any practical complaints of inefficiency in this section of the code but if there are demonstrable, live scenarios were this is a problem then it should definitely be addressed.

**Comment by tristanharris** [comment]
The original problem is if eg name is set to 'abc=xyz' then the MT returns '=name=abc=zyx'. The current code turns this into 'name' => 'abc' (loosing the end of the value). So keeping the regex means having split on all '=' we need to re-join all but the first part which starts making that messy, imho. Whereas the explode (with a limit) means we only ever split on one '='

**Pull request closed without merging**
